version: '3.8'

services:
  microservice:
    build: ./microservice
    command: uvicorn app.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./microservice:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
